const TRANSLATIONS = {
  // Américas
  'Argentina': 'Argentina',
  'Bolivia': 'Bolivia',
  'Brazil': 'Brasil',
  'Canada': 'Canadá',
  'Chile': 'Chile',
  'Colombia': 'Colombia',
  'Costa Rica': 'Costa Rica',
  'Ecuador': 'Ecuador',
  'El Salvador': 'El Salvador',
  'Guatemala': 'Guatemala',
  'Honduras': 'Honduras',
  'Jamaica': 'Jamaica',
  'Mexico': 'México',
  'Panama': 'Panamá',
  'Paraguay': 'Paraguay',
  'Peru': 'Perú',
  'Trinidad and Tobago': 'Trinidad y Tobago',
  'United States': 'Estados Unidos',
  'USA': 'EE.UU.',
  'Uruguay': 'Uruguay',
  'Venezuela': 'Venezuela',
  'New Zealand': 'Nueva Zelanda',

  // Europa
  'Albania': 'Albania',
  'Austria': 'Austria',
  'Belgium': 'Bélgica',
  'Bosnia and Herzegovina': 'Bosnia y Herzegovina',
  'Bosnia': 'Bosnia',
  'Bulgaria': 'Bulgaria',
  'Croatia': 'Croacia',
  'Czech Republic': 'República Checa',
  'Czechia': 'República Checa',
  'Denmark': 'Dinamarca',
  'England': 'Inglaterra',
  'Finland': 'Finlandia',
  'France': 'Francia',
  'Germany': 'Alemania',
  'Greece': 'Grecia',
  'Hungary': 'Hungría',
  'Iceland': 'Islandia',
  'Ireland': 'Irlanda',
  'Italy': 'Italia',
  'Kosovo': 'Kosovo',
  'Netherlands': 'Países Bajos',
  'North Macedonia': 'Macedonia del Norte',
  'Norway': 'Noruega',
  'Poland': 'Polonia',
  'Portugal': 'Portugal',
  'Romania': 'Rumanía',
  'Russia': 'Rusia',
  'Scotland': 'Escocia',
  'Serbia': 'Serbia',
  'Slovakia': 'Eslovaquia',
  'Slovenia': 'Eslovenia',
  'Spain': 'España',
  'Sweden': 'Suecia',
  'Switzerland': 'Suiza',
  'Turkey': 'Turquía',
  'Türkiye': 'Turquía',
  'Ukraine': 'Ucrania',
  'Wales': 'Gales',

  // África
  'Algeria': 'Argelia',
  'Angola': 'Angola',
  'Cameroon': 'Camerún',
  "Côte d'Ivoire": 'Costa de Marfil',
  'Ivory Coast': 'Costa de Marfil',
  'DR Congo': 'RD Congo',
  'Democratic Republic of the Congo': 'RD Congo',
  'Egypt': 'Egipto',
  'Ghana': 'Ghana',
  'Guinea': 'Guinea',
  'Mali': 'Malí',
  'Morocco': 'Marruecos',
  'Nigeria': 'Nigeria',
  'Senegal': 'Senegal',
  'South Africa': 'Sudáfrica',
  'Tunisia': 'Túnez',

  // Asia / Oceanía
  'Australia': 'Australia',
  'China': 'China',
  'Indonesia': 'Indonesia',
  'Iran': 'Irán',
  'Iraq': 'Irak',
  'Japan': 'Japón',
  'Jordan': 'Jordania',
  'Kazakhstan': 'Kazajistán',
  'North Korea': 'Corea del Norte',
  'Oman': 'Omán',
  'Palestine': 'Palestina',
  'Qatar': 'Catar',
  'Saudi Arabia': 'Arabia Saudita',
  'South Korea': 'Corea del Sur',
  'Korea': 'Corea del Sur',
  'Korea Republic': 'Corea del Sur',
  'Cape Verde': 'Cabo Verde',
  'Cabo Verde': 'Cabo Verde',
  'Syria': 'Siria',
  'Thailand': 'Tailandia',
  'United Arab Emirates': 'Emiratos Árabes Unidos',
  'UAE': 'EAU',
  'Uzbekistan': 'Uzbekistán',
  'Vietnam': 'Vietnam',
}

export function translateTeam(name) {
  if (!name) return name
  return TRANSLATIONS[name] ?? name
}

export function translatePartido(partido) {
  if (!partido) return partido
  return {
    ...partido,
    local:     translateTeam(partido.local),
    visitante: translateTeam(partido.visitante),
  }
}
